// flow-typed signature: 5fc94d041943551f55f4733e57f1df66
// flow-typed version: <<STUB>>/node-todo-server_v^0.0.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-todo-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-todo-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-todo-server/app' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-todo-server/app.js' {
  declare module.exports: $Exports<'node-todo-server/app'>;
}
